# .bash_profile

if [ -f ~/.bashrc ]; then
    . ~/.bashrc
fi

if [ -f ~/.bash_local ]; then
    . ~/.bash_local
fi

PATH=$PATH:$HOME/bin
export PATH

# NVM
if [ -f /usr/local/opt/nvm/nvm.sh ]; then
    export NVM_DIR=~/.nvm
    . /usr/local/opt/nvm/nvm.sh
fi

# Bash completion
if [ -f /usr/local/etc/bash_completion ]; then
    . /usr/local/etc/bash_completion
fi

# Git prompt
if [ -f /usr/share/git-core/contrib/completion/git-prompt.sh ]; then
    . /usr/share/git-core/contrib/completion/git-prompt.sh
fi

# Git prompt config
if [[ -n `type __git_ps1` ]]; then
    GIT_PS1_SHOWDIRTYSTATE=1
    GIT_PS1_SHOWSTASHSTATE=1
    GIT_PS1_SHOWUNTRACKEDFILES=1
    GIT_PS1_SHOWUPSTREAM="verbose"
    # GIT_PS1_STATESEPERATOR=SP
    GIT_PS1_SHOWCOLORHINTS=1
    # PS1='[\W$(__git_ps1 " (%s)")]\n\T \$ '
    PROMPT_COMMAND='__git_ps1 "\n\w" "\n\T \$ "'
fi

# Readline settings
# NOTE: Bind is used instead of setting these in .inputrc.
bind "set bell-style none"              # No bell (the sound)
bind "set completion-ignore-case on"    # Ignore case in bash completion
bind "set show-all-if-ambiguous On"     # Automatically show completion without double-tab-ing

# History settings
export HISTFILE=~/.bash_history
export HISTFILESIZE=20000
export HISTCONTROL=ignoreboth
shopt -s histappend

# Aliases
alias clr="clear && clear"
alias ll="ls -ltrG"
alias lla="ll -a"
alias ..="cd .."
alias resource=". ~/.bash_profile"

md() { mkdir -pv "$@" && cd "$_"; }

# RVM - RVM wants to go last
if [[ -s ~/.rvm/scripts/rvm ]]; then
    # Load RVM into a shell session *as a function*
    . ~/.rvm/scripts/rvm
fi
