# If you come from bash you might have to change your $PATH.

PATH=$PATH:./node_modules/.bin
PATH=$PATH:~/bin

PATH=$HOME/.cargo/bin:$PATH
PATH=/Library/Frameworks/Python.framework/Versions/3.7/bin:$PATH
PATH=/usr/local/opt/ruby/bin:$PATH

export GOPATH=$HOME/.go
PATH=$PATH:$GOPATH/bin

export PATH

# Path to your oh-my-zsh installation.
export ZSH="/Users/matt/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/robbyrussell/oh-my-zsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git gitfast thefuck zsh_reload)

source $ZSH/oh-my-zsh.sh

# fnm
# @see https://github.com/Schniz/fnm#zsh
eval "$(fnm env)"

# Git prompt config
if [[ -n `type __git_ps1` ]]; then
    GIT_PS1_SHOWDIRTYSTATE=1
    GIT_PS1_SHOWSTASHSTATE=1
    GIT_PS1_SHOWUNTRACKEDFILES=1
    GIT_PS1_SHOWUPSTREAM="verbose"
    GIT_PS1_SHOWCOLORHINTS=1
    precmd () { __git_ps1 $'\n'"%~" $'\n'"%* $ "}
fi

# Homebrew completions
# @see https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
if type brew &>/dev/null; then
  FPATH=$(brew --prefix)/share/zsh/site-functions:$FPATH

  autoload -Uz compinit
  compinit
fi

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

alias clr="reset"
alias ll="ls -ltrG"
alias lla="ll -a"
alias ..="cd .."

alias lsnm="find . -name 'node_modules' -type d -prune"
alias rmnm="lsnm -exec rm -rf '{}' +"

# gnumfmt isn't preinstalled on macOS, so `brew install coreutils` first
function sizes {
  echo "minified  gzipped  filename"
  echo "========  =======  ========"

  tm=0
  tg=0

  for file in "$@"
  do
    m=$(cat $file | wc -c)
    g=$(gzip -9 -c $file | wc -c)

    tm=$(($tm + $m))
    tg=$(($tg + $g))

    minified=$(gnumfmt --to=iec --suffix=B "$m")
    gzipped=$(gnumfmt --to=iec --suffix=B "$g")
    printf "%8s %8s  %s\n" $minified $gzipped $file
  done

  echo "========  =======  ========"
  totalMinified=$(gnumfmt --to=iec --suffix=B "$tm")
  totalGzipped=$(gnumfmt --to=iec --suffix=B "$tg")
  printf "%8s %8s  %s\n" $totalMinified $totalGzipped "*total*"
}
